# Infrastructure as Code for a containerized web service
# spec: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: roman-numeral-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/avardaan/roman-numeral-service
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    # rootDir: default to root of repo
