services:
  # A containerized roman numeral web service
  - type: web
    name: roman-numeral-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/avardaan/roman-numeral-service # optional
    region: oregon
    plan: free
    branch: main
    numInstances: 1 # optional (defaults to 1)
    # rootDir: default to root of repo
